---
- name: include python vars
  include_vars: 
    file: main.yml
    name: vars

- name: ensure python3 is installed
  become: yes
  yum:
      name: python3
      state: latest

- name: ensure pip available
  become: yes
  yum:
      name: python3-pip
      state: present

- name: ensure virtualenv available for python3
  become: yes
  pip:
      name: virtualenv
      executable: pip3


- name: ensure packages installed
  become: yes
  when: vars.packages
  pip:
      name: "{{ packages }}"
      executable: pip3
  vars:
      packages: "{{ vars.packages }}"
